window.__GM_I18N={
"Satılık & Kiralık İlanlar · Konut, Ofis, Arsa — Meridyen Gayrimenkul":{"en":"For-Sale & For-Rent Listings · Homes, Offices, Land — Meridyen Gayrimenkul","ru":"Объявления о продаже и аренде · Жильё, офисы, земля — Meridyen Gayrimenkul","zh":"出售与出租房源 · 住宅、办公室、土地 — Meridyen Gayrimenkul","ar":"إعلانات للبيع والإيجار · مساكن ومكاتب وأراضٍ — Meridyen Gayrimenkul"},
"Satılık & Kiralık İlanlar — Meridyen Gayrimenkul":{"en":"For-Sale & For-Rent Listings — Meridyen Gayrimenkul","ru":"Объявления о продаже и аренде — Meridyen Gayrimenkul","zh":"出售与出租房源 — Meridyen Gayrimenkul","ar":"إعلانات للبيع والإيجار — Meridyen Gayrimenkul"},
"İzmir ve Ege'de EİDS onaylı satılık & kiralık konut, ofis, dükkan ve arsa ilanları. Her ilanda gerçek konum, kapsamlı özellik tablosu ve şeffaf fiyat. Meridyen Gayrimenkul.":{"en":"EİDS-verified for-sale & for-rent listings of homes, offices, shops and land across İzmir and the Aegean. A real location, a comprehensive feature table and a transparent price on every listing. Meridyen Gayrimenkul.","ru":"Проверенные EİDS объявления о продаже и аренде жилья, офисов, магазинов и земли в İzmir и на Эгейском побережье. В каждом объявлении — реальное расположение, подробная таблица характеристик и прозрачная цена. Meridyen Gayrimenkul.","zh":"İzmir 与爱琴海地区经 EİDS 认证的出售与出租住宅、办公室、店铺和土地房源。每条房源均有真实位置、详尽特征表和透明价格。Meridyen Gayrimenkul。","ar":"إعلانات موثّقة من EİDS للبيع والإيجار لمساكن ومكاتب ومحلات وأراضٍ في İzmir وبحر إيجه. موقع حقيقي وجدول مواصفات شامل وسعر شفاف في كل إعلان. Meridyen Gayrimenkul."},
"EİDS onaylı satılık & kiralık gayrimenkul ilanları — konut, ofis, arsa. Gerçek konum, kapsamlı detay, şeffaf fiyat.":{"en":"EİDS-verified for-sale & for-rent property listings — homes, offices, land. Real location, comprehensive detail, transparent price.","ru":"Проверенные EİDS объявления о продаже и аренде недвижимости — жильё, офисы, земля. Реальное расположение, подробные детали, прозрачная цена.","zh":"经 EİDS 认证的出售与出租房产房源——住宅、办公室、土地。真实位置、详尽细节、透明价格。","ar":"إعلانات عقارية موثّقة من EİDS للبيع والإيجار — مساكن ومكاتب وأراضٍ. موقع حقيقي وتفاصيل شاملة وسعر شفاف."},
"EİDS Onaylı İlanlar":{"en":"EİDS-Verified Listings","ru":"Объявления, проверенные EİDS","zh":"EİDS 认证房源","ar":"إعلانات موثّقة من EİDS"},
"Satılık & Kiralık Gayrimenkul İlanları":{"en":"Properties for Sale & Rent","ru":"Недвижимость: продажа и аренда","zh":"出售与出租房产","ar":"عقارات للبيع والإيجار"},
"İzmir ve Ege'de konut, ofis, dükkan ve arsa portföyümüz. Her ilan EİDS yetki belgesiyle yayında; gerçek konum haritası, sahibinden düzeyinde kapsamlı özellik tablosu ve şeffaf fiyatla.":{"en":"Our portfolio of homes, offices, shops and land across İzmir and the Aegean. Every listing is published with an EİDS authorization certificate; with a real location map, a comprehensive feature table at sahibinden level, and a transparent price.","ru":"Наш портфель жилья, офисов, магазинов и земли в İzmir и на Эгейском побережье. Каждое объявление публикуется с разрешительным документом EİDS; с реальной картой расположения, подробной таблицей характеристик уровня sahibinden и прозрачной ценой.","zh":"我们在 İzmir 与爱琴海地区的住宅、办公室、店铺和土地房源。每条房源均凭 EİDS 授权证书发布；配有真实位置地图、达到 sahibinden 水准的详尽特征表和透明价格。","ar":"محفظتنا من المساكن والمكاتب والمحلات والأراضي في İzmir وبحر إيجه. كل إعلان منشور بشهادة تفويض EİDS؛ بخريطة موقع حقيقية، وجدول مواصفات شامل بمستوى sahibinden، وسعر شفاف."}
};
